# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            public_url: '%env(BASE_URL)%/uploads'
            options:
                directory: '%kernel.project_dir%/public/uploads'
