vich_uploader:
    db_driver: orm
    storage: flysystem

    metadata:
        type: attribute

    mappings:
        courses:
            upload_destination: default.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
